// Generated by CoffeeScript 1.9.1

/*
This is separate Eco template for Clinch processor
 */

(function() {
  var Eco, extension, processor;

  Eco = require('eco');

  extension = '.eco';

  processor = function(data, filename, cb) {
    var content, error;
    try {
      content = Eco.precompile(data);
    } catch (_error) {
      error = _error;
      error.filename = filename;
      return cb(error);
    }
    return cb(null, "module.exports = " + content);
  };

  module.exports = {
    extension: extension,
    processor: processor
  };

}).call(this);
